name: CI

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  # push:
  #   branches: [feat/light-house]
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "12"
      - uses: actions/setup-node@v2
      - run: sudo npm install -g @lhci/cli@0.7.x
      - run: sudo npm install -g serve
      - run: yarn
      - run: yarn build
      - run: lhci autorun --collect.startServerCommand="serve -s dist"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
