name: CI

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [feat/light-house]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn && yarn global add @lhci/cli@0.7.x
      - run: yarn build
      - run: lhci autorun
